# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('steam_app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default="!!! DON'T TOUCH !!!", help_text='This field will be filled automatically by synchronizing with Steam.', max_length=255)),
                ('localization_status', models.TextField(blank=True)),
                ('review_summary', models.TextField()),
                ('review_detail', models.TextField(blank=True)),
                ('review_detail_link', models.CharField(blank=True, max_length=255)),
                ('localized_by_developer', models.BooleanField(default=False)),
                ('localized_by_community', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('invalid', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
