# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(db_index=True, default="!!! DON'T TOUCH !!!", help_text='This field will be filled automatically by synchronizing with Steam.', max_length=255),
        ),
    ]
